gText_WouldYouLikeToSaveTheGame::
	.string "Velisne ludum servare?$"

gText_AlreadySaveFile_WouldLikeToOverwrite::
	.string "Fasciculus iam exstat.\n"
	.string "Licetne superscribere?$"

gText_SavingDontTurnOffThePower::
	.string "SERVANS…\n"
	.string "NOLI EXTINGUERE VIM MACHINAE.$"

gText_PlayerSavedTheGame::
	.string "{PLAYER} ludum servavit.$"

gText_SaveFailed2::
	.string "セーブに　しっぱい　しました‥$"

gText_DifferentGameFile::
	.string "WARNING!\p"
	.string "There is a different game file that\n"
	.string "is already saved.\p"
	.string "If you save now, the other file's\n"
	.string "adventure, including items and\l"
	.string "POKéMON, will be entirely lost.\p"
	.string "Are you sure you want to save now\n"
	.string "and overwrite the other save file?$"
