@ For the NPC in Pallet Town that talks about the Trainer Tips sign

PalletTown_Text_HmmIsThatRight::
	.string "…\n"
	.string "Itane est…?$"

PalletTown_Text_OhLookLook::
	.string "Ehem!\n"
	.string "Vide, vide!$"

PalletTown_Text_ReadItReadIt::
	.string "Lege, lege!$"

@ Used by sign
PalletTown_Text_PressStartToOpenMenu::
	.string "TRAINER TIPS\p"
	.string "Preme START to open the MENU!$"

PalletTown_Text_SignsAreUsefulArentThey::
	.string "Nonne signa utilia sunt?$"

PalletTown_Text_LookCopiedTrainerTipsSign::
	.string "Vide, vide!\p"
	.string "transcripsi quod dixit one of\n"
	.string "those TRAINER TIPS signs!$"

@ Used by NPC
PalletTown_Text_PressStartToOpenMenuCopy::
	.string "TRAINER TIPS!\p"
	.string "Preme START aperire the MENU!$"
