PalletTown_PlayersHouse_1F_Text_AllBoysLeaveOakLookingForYou::
    .string "MAT.: …Sane.\n"
    .string "Omnes pueri aliquando domo exeunt.\l"
    .string "Sic dixit televisio.\p"
    .string "Ah. PROF. Quercus, vicinus,\n"
    .string "te quaerebat.$"

PalletTown_PlayersHouse_1F_Text_AllGirlsLeaveOakLookingForYou::
    .string "MAT.: …Sane.\n"
    .string "Omnes puellae peregrinari cupiunt.\l"
    .string "Sic dixit televisio.\p"
    .string "Ah. PROF. Quercus, vicinus,\n"
    .string "te quaerebat.$"

PalletTown_PlayersHouse_1F_Text_YouShouldTakeQuickRest::
    .string "MAT.: {PLAYER}!\n"
    .string "Paulum requiescere debes.$"

PalletTown_PlayersHouse_1F_Text_LookingGreatTakeCare::
    .string "MAT.: Bene! Tu et POKéMONa\n"
    .string "tua optime videmini.\l"
    .string "Optima fortuna tecum sit!$"

PalletTown_PlayersHouse_1F_Text_MovieOnTVFourBoysOnRailroad::
    .string "Est fabula in televisione.\n"
    .string "Quattor pueri in via\l"
    .string "ambulant.\p"
    .string "…etiam mihi ire oportet.$"

PalletTown_PlayersHouse_1F_Text_MovieOnTVGirlOnBrickRoad::
    .string "Est fabula in televisione.\n"
    .string "Puella flavis capillis\l"
    .string "in via lapidea ambulat.\p"
    .string "…etiam mihi ire oportet.$"

PalletTown_PlayersHouse_1F_Text_OopsWrongSide::
    .string "Vah, latus falsum…$"

