PalletTown_Text_OakDontGoOut::
    .string "OAK: Heus! Mane!\n"
    .string "Noli egredi!$"

PalletTown_Text_OakGrassUnsafeNeedMon::
    .string "OAK: Non tutum ibi est! Fera\n"
    .string "POKéMONa gramen altum incolunt!\p"
    .string "Necesse est tibi habere\n"
    .string "POKéMONa pro praesidio.\p"
    .string "Scio quid faciendum sit!\n"
    .string "Sequere me!$"

PalletTown_Text_RaisingMonsToo::
    .string "Ego etiam POKéMONa educo.\p"
    .string "Cum viguerint, me defendere\n"
    .string "poterunt.$"

PalletTown_Text_CanStoreItemsAndMonsInPC::
    .string "Quam mirabile artificium est!\p"
    .string "You can now store and recall items\n"
    .string "and POKéMON as data via PC.$"

PalletTown_Text_OakPokemonResearchLab::
    .string "OAK POKéMON RESEARCH LAB$"

PalletTown_Text_PlayersHouse::
    .string "Domus tua$"

PalletTown_Text_RivalsHouse::
    .string "Domus aemuli tui$"

PalletTown_Text_TownSign::
    .string "PALLET TOWN\n"
    .string "Shades of your journey await!$"

PalletTown_Text_OakLetMeSeePokedex::
    .string "OAK: Ah, {PLAYER}!\n"
    .string "You're back, are you?\p"
    .string "How much have you filled in your\n"
    .string "POKéDEX?\p"
    .string "May I see it?\p"
    .string "Videamus…$"

PalletTown_Text_CaughtXPuttingInHonestEffort::
    .string "Cepisti {STR_VAR_2}…\p"
    .string "Hm, videtur as if you're putting\n"
    .string "in an honest effort.\p"
    .string "When you manage to fill it some\n"
    .string "more, come show me, please.$"

PalletTown_Text_CaughtXImpressiveFollowMe::
    .string "Cepisti… {STR_VAR_2}!?\n"
    .string "Now, this is impressive!\p"
    .string "Aliquid te rogare velim,\n"
    .string "{PLAYER}.\p"
    .string "Veni.\n"
    .string "Sequere me.$"

PalletTown_Text_OakYouEnjoyingTraveling::
    .string "OAK: Ah, {PLAYER}!\n"
    .string "You seem to be enjoying traveling.\p"
    .string "Knowing you, {PLAYER}, I can easily\n"
    .string "imagine you going out to even more\l"
    .string "exotic locales.\p"
    .string "Good for you, good for you.\n"
    .string "Hohoho.$"

